#!/bin/bash
#
# Start untuk program EWS
#
# Create Tri Miyarno
#########################################################################



case $1 in
	"start")
		printf "Starting EWS Server ...\n"
		error=0
		sleep 10
		java -jar /usr/local/lib/dews&
		exit $error
		;;

	"restart")
		printf "Restart EWS Server ...\n"
		sleep 10
		echo "Stop EWS Server....."
		killall -TERM java
		sleep 10
		echo "Start EWS Server....."
		java -jar /usr/local/lib/dews&
		error=0
		exit $error
		;;

	"stop")
		printf "Stop EWS Server ...\n"
		killall -TERM java
		#pid=`ps aux | grep dews | awk '{print $2}'`
		#pid =`pidof java | awk '{print $2}'`
		#kill $pid
		error=0
		exit $?
		;;

	*)	
		printf "Bantuan .....? \n"
		echo "untuk memulai ketikan start"
		echo "untuk berhenti ketikan stop"
		echo "untuk restart ketikan restart"
		echo " "
		;;
esac
